// Manatee County entities, cities, neighborhoods, and zip codes
export const manateeCountySlugs = new Set([
  "34201",
  "34202",
  "34203",
  "34204",
  "34205",
  "34206",
  "34207",
  "34208",
  "34209",
  "34210",
  "34211",
  "34212",
  "34213",
  "34214",
  "34215",
  "34216",
  "34217",
  "34218",
  "34219",
  "34220",
  "34221",
  "34222",
  "34223",
  "34224",
  "34225",
  "34226",
  "34227",
  "34228",
  "34229",
  "34230",
  "34231",
  "34232",
  "34233",
  "34234",
  "34235",
  "34236",
  "34237",
  "34238",
  "34239",
  "34240",
  "34241",
  "34242",
  "34243",
  "34244",
  "34245",
  "34246",
  "34247",
  "34248",
  "34249",
  "34250",
  "34251",
  "34252",
  "34253",
  "34254",
  "34255",
  "34256",
  "34257",
  "34258",
  "34259",
  "34260",
  "34261",
  "34262",
  "34263",
  "34264",
  "34265",
  "34266",
  "34267",
  "34268",
  "34269",
  "34270",
  "34271",
  "34272",
  "34273",
  "34274",
  "34275",
  "34276",
  "34277",
  "34278",
  "34279",
  "34280",
  "34281",
  "34282",
  "34283",
  "34284",
  "34285",
  "34286",
  "34287",
  "34288",
  "34289",
  "34290",
  "34291",
  "34292",
  "34293",
  "34294",
  "34295",
  "34296",
  "34297",
  "34298",
  "34299",
  "anna-maria-fl",
  "bay-anna-maria-fl",
  "bay-bradenton-beach-fl",
  "bay-holmes-beach-fl",
  "bay-lakewood-ranch-fl",
  "bay-palmetto-fl",
  "bay-parrish-fl",
  "bayshore-gardens-fl",
  "bradenton-beach-fl",
  "bradenton-fl",
  "cortez-fl",
  "cove-anna-maria-fl",
  "cove-bradenton-beach-fl",
  "cove-holmes-beach-fl",
  "cove-lakewood-ranch-fl",
  "cove-palmetto-fl",
  "cove-parrish-fl",
  "crest-anna-maria-fl",
  "crest-bradenton-beach-fl",
  "crest-holmes-beach-fl",
  "crest-lakewood-ranch-fl",
  "crest-palmetto-fl",
  "crest-parrish-fl",
  "downtown-anna-maria-fl",
  "downtown-bradenton-beach-fl",
  "downtown-holmes-beach-fl",
  "downtown-lakewood-ranch-fl",
  "downtown-palmetto-fl",
  "downtown-parrish-fl",
  "east-anna-maria-fl",
  "east-bradenton-beach-fl",
  "east-holmes-beach-fl",
  "east-lakewood-ranch-fl",
  "east-palmetto-fl",
  "east-parrish-fl",
  "ellenton-fl",
  "estates-anna-maria-fl",
  "estates-bradenton-beach-fl",
  "estates-holmes-beach-fl",
  "estates-lakewood-ranch-fl",
  "estates-palmetto-fl",
  "estates-parrish-fl",
  "gardens-anna-maria-fl",
  "gardens-bradenton-beach-fl",
  "gardens-holmes-beach-fl",
  "gardens-lakewood-ranch-fl",
  "gardens-palmetto-fl",
  "gardens-parrish-fl",
  "harbour-anna-maria-fl",
  "harbour-bradenton-beach-fl",
  "harbour-holmes-beach-fl",
  "harbour-lakewood-ranch-fl",
  "harbour-palmetto-fl",
  "harbour-parrish-fl",
  "hills-anna-maria-fl",
  "hills-bradenton-beach-fl",
  "hills-holmes-beach-fl",
  "hills-lakewood-ranch-fl",
  "hills-palmetto-fl",
  "hills-parrish-fl",
  "historic-anna-maria-fl",
  "historic-bradenton-beach-fl",
  "historic-holmes-beach-fl",
  "historic-lakewood-ranch-fl",
  "historic-palmetto-fl",
  "historic-parrish-fl",
  "holmes-beach-fl",
  "isles-anna-maria-fl",
  "isles-bradenton-beach-fl",
  "isles-holmes-beach-fl",
  "isles-lakewood-ranch-fl",
  "isles-palmetto-fl",
  "isles-parrish-fl",
  "key-anna-maria-fl",
  "key-bradenton-beach-fl",
  "key-holmes-beach-fl",
  "key-lakewood-ranch-fl",
  "key-palmetto-fl",
  "key-parrish-fl",
  "lakewood-ranch-fl",
  "landing-anna-maria-fl",
  "landing-bradenton-beach-fl",
  "landing-holmes-beach-fl",
  "landing-lakewood-ranch-fl",
  "landing-palmetto-fl",
  "landing-parrish-fl",
  "longboat-key-fl",
  "lower-anna-maria-fl",
  "lower-bradenton-beach-fl",
  "lower-holmes-beach-fl",
  "lower-lakewood-ranch-fl",
  "lower-palmetto-fl",
  "lower-parrish-fl",
  "manatee-county",
  "manor-anna-maria-fl",
  "manor-bradenton-beach-fl",
  "manor-holmes-beach-fl",
  "manor-lakewood-ranch-fl",
  "manor-palmetto-fl",
  "manor-parrish-fl",
  "memphis-fl",
  "myakka-city-fl",
  "new-anna-maria-fl",
  "new-bradenton-beach-fl",
  "new-holmes-beach-fl",
  "new-lakewood-ranch-fl",
  "new-palmetto-fl",
  "new-parrish-fl",
  "north-anna-maria-fl",
  "north-bradenton-beach-fl",
  "north-holmes-beach-fl",
  "north-lakewood-ranch-fl",
  "north-palmetto-fl",
  "north-parrish-fl",
  "oaks-anna-maria-fl",
  "oaks-bradenton-beach-fl",
  "oaks-holmes-beach-fl",
  "oaks-lakewood-ranch-fl",
  "oaks-palmetto-fl",
  "oaks-parrish-fl",
  "old-anna-maria-fl",
  "old-bradenton-beach-fl",
  "old-holmes-beach-fl",
  "old-lakewood-ranch-fl",
  "old-palmetto-fl",
  "old-parrish-fl",
  "palmetto-fl",
  "palms-anna-maria-fl",
  "palms-bradenton-beach-fl",
  "palms-holmes-beach-fl",
  "palms-lakewood-ranch-fl",
  "palms-palmetto-fl",
  "palms-parrish-fl",
  "park-anna-maria-fl",
  "park-bradenton-beach-fl",
  "park-holmes-beach-fl",
  "park-lakewood-ranch-fl",
  "park-palmetto-fl",
  "park-parrish-fl",
  "parrish-fl",
  "plaza-anna-maria-fl",
  "plaza-bradenton-beach-fl",
  "plaza-holmes-beach-fl",
  "plaza-lakewood-ranch-fl",
  "plaza-palmetto-fl",
  "plaza-parrish-fl",
  "pointe-anna-maria-fl",
  "pointe-bradenton-beach-fl",
  "pointe-holmes-beach-fl",
  "pointe-lakewood-ranch-fl",
  "pointe-palmetto-fl",
  "pointe-parrish-fl",
  "ridge-anna-maria-fl",
  "ridge-bradenton-beach-fl",
  "ridge-holmes-beach-fl",
  "ridge-lakewood-ranch-fl",
  "ridge-palmetto-fl",
  "ridge-parrish-fl",
  "samoset-fl",
  "shores-anna-maria-fl",
  "shores-bradenton-beach-fl",
  "shores-holmes-beach-fl",
  "shores-lakewood-ranch-fl",
  "shores-palmetto-fl",
  "shores-parrish-fl",
  "south-anna-maria-fl",
  "south-bradenton-beach-fl",
  "south-bradenton-fl",
  "south-holmes-beach-fl",
  "south-lakewood-ranch-fl",
  "south-palmetto-fl",
  "south-parrish-fl",
  "terrace-anna-maria-fl",
  "terrace-bradenton-beach-fl",
  "terrace-holmes-beach-fl",
  "terrace-lakewood-ranch-fl",
  "terrace-palmetto-fl",
  "terrace-parrish-fl",
  "upper-anna-maria-fl",
  "upper-bradenton-beach-fl",
  "upper-holmes-beach-fl",
  "upper-lakewood-ranch-fl",
  "upper-palmetto-fl",
  "upper-parrish-fl",
  "village-anna-maria-fl",
  "village-bradenton-beach-fl",
  "village-holmes-beach-fl",
  "village-lakewood-ranch-fl",
  "village-palmetto-fl",
  "village-parrish-fl",
  "west-anna-maria-fl",
  "west-bradenton-beach-fl",
  "west-bradenton-fl",
  "west-holmes-beach-fl",
  "west-lakewood-ranch-fl",
  "west-palmetto-fl",
  "west-parrish-fl",
  "west-samoset-fl",
  "whitfield-fl",
]);

export const manateeCityNames = [
  "bradenton",
  "lakewood ranch",
  "palmetto",
  "parrish",
  "ellenton",
  "anna maria",
  "holmes beach",
  "bradenton beach",
  "longboat key",
  "myakka city",
  "bayshore gardens",
  "cortez",
  "memphis",
  "samoset",
  "south bradenton",
  "west bradenton",
  "west samoset",
  "whitfield",
  "terra ceia",
  "palma sola",
  "duette",
  "rubonia",
  "tallevast",
];

/**
 * Determines whether a given location slug or city name belongs to Manatee County, FL.
 */
export function isManateeCounty(loc_slug: string, clean_name: string = ''): boolean {
  const s = (loc_slug || '').toLowerCase().trim();
  const c = (clean_name || '').toLowerCase().trim();

  // Exclude false friends
  if (s.includes('palmetto-bay') || s.includes('palmetto-estates') || s.includes('manatee-road')) {
    return false;
  }
  if (c.includes('palmetto bay') || c.includes('palmetto estates') || c.includes('manatee road')) {
    return false;
  }

  // Check explicit county
  if (s === 'manatee-county' || c.includes('manatee county')) {
    return true;
  }

  // Check known slug set
  if (manateeCountySlugs.has(s)) {
    return true;
  }

  // Check city names match
  for (const city of manateeCityNames) {
    if (c === city || c.startsWith(city + ' ') || c.endsWith(' ' + city) || c.includes(city)) {
      return true;
    }
    const dashed = city.replace(/ /g, '-');
    if (s === dashed + '-fl' || s.endsWith('-' + dashed + '-fl') || s.startsWith(dashed + '-')) {
      return true;
    }
  }

  return false;
}

export interface ManateeHub {
  name: string;
  slug: string;
}

export const manateeKeyHubs: ManateeHub[] = [
  { name: 'Bradenton', slug: 'bradenton-fl' },
  { name: 'Lakewood Ranch', slug: 'lakewood-ranch-fl' },
  { name: 'Palmetto', slug: 'palmetto-fl' },
  { name: 'Parrish', slug: 'parrish-fl' },
  { name: 'Ellenton', slug: 'ellenton-fl' },
  { name: 'Anna Maria', slug: 'anna-maria-fl' },
  { name: 'Holmes Beach', slug: 'holmes-beach-fl' },
  { name: 'Bradenton Beach', slug: 'bradenton-beach-fl' },
  { name: 'Longboat Key', slug: 'longboat-key-fl' },
  { name: 'Bayshore Gardens', slug: 'bayshore-gardens-fl' },
  { name: 'Cortez', slug: 'cortez-fl' },
  { name: 'Myakka City', slug: 'myakka-city-fl' },
  { name: 'South Bradenton', slug: 'south-bradenton-fl' },
  { name: 'West Bradenton', slug: 'west-bradenton-fl' },
  { name: 'Samoset', slug: 'samoset-fl' },
  { name: 'Whitfield', slug: 'whitfield-fl' },
];
